#!/bin/sh

# Exit script on failures
set -e

# Configure
git config --global user.name "10hendersonm"
git config --global user.email "10hendersonm@gmail.com"

# Create release
npx standard-version --releaseCommitMessageFormat "chore(release): {{currentTag}} [SKIP CI]"

# Push to GitHub
git push --follow-tags origin main

# Release to npm
npm publish