#!/bin/sh

set -e # Exit on failures
set -x # Display input commands

# Configure Git
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
git config --local user.name "$GH_USER"
git config --local user.email "$GH_EMAIL"
git remote set-url origin "https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY"

# Create the release
npx standard-version --releaseCommitMessageFormat "chore(release): {{currentTag}} [skip ci]"

# Push the release
git push --follow-tags origin $GIT_BRANCH

# Configure NPM
npm set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"

# Publish
npm publish
