name: CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Load Deployment
        uses: actions/cache@v2
        env:
          cache-name: deployment-cache
        with:
          path: './**/*'
          key: ${{ github.event.workflow_run.head_sha }} # commit hash

      - name: Release
        env:
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/release
