name: CICD
on: [push]
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: Install Dependencies
        run: npm ci

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/release
