name: CICD
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set Up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: Install Dependencies
        run: npm ci

  CD:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Release
        run: ./scripts/release
