name: CICD
on: [push]
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: Install Dependencies
        run: npm ci

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.name "10hendersonm"
          git config --local user.email "10hendersonm@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          npx standard-version --releaseCommitMessageFormat "chore(release): {{currentTag}} [skip ci]"
          git push --follow-tags origin main
          npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish
